---
inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - git-duet.gemspec
    - Rakefile
    - Gemfile
Documentation:
  Enabled: false

FileName:
  Enabled: false

DoubleNegation:
  Enabled: false
